### ISSUE TITLE
ticket to get an image

### ISSUE THREAD

**Issue by markherringer** [healthsites/hcid-watchkeeper#31]
![computer_guy](https://cloud.githubusercontent.com/assets/38838/13248395/b3317680-da26-11e5-86cf-23cbbcce9da5.jpg)

![user1](https://cloud.githubusercontent.com/assets/38838/13248400/b95296ac-da26-11e5-9043-8deddcc8dcf5.jpg)

![data-input](https://cloud.githubusercontent.com/assets/38838/13248406/c09378aa-da26-11e5-967e-e8bf2c9d2828.jpg)

**Comment by cchristelis** [comment]
@markherringer, we can re-open this when we need to add additional images, but for now I'm closing...
