### ISSUE TITLE
short term update

### ISSUE THREAD

**Issue by markherringer** [healthsites/hcid-watchkeeper#7]
1) establish staging.hcid.kartoza.com
2) Change the logo
3) Update the menu items

**Comment by cchristelis** [comment]
http://staging.watchkeeper.kartoza.com/alert

Update alert form with these fields:

link to assessment report  
assessment date  
assessors name  
assessors organisation

Notes:
Remove the + sign on the add alert form as it is already open

**Comment by cchristelis** [comment]
This is done and live at http://staging.hcid.kartoza.com/

**Comment by cchristelis** [comment]
@markherringer, I'm having trouble with having hcid-watchkeeper vs watchkeeper in my account, as github thinks these are the same. We will have to de-couple the projects in some way. Let's chat when you are back in the office.

Also I can't close these issues, maybe you can consider upping my permissions on this project?
